# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lift the Bar Education
description: > # this means to ignore newlines until "baseurl:"
  A Habit-Based, Personal Trainer Education.
baseurl: "/LTB_Education" # the subpath of your site, e.g. /blog
url: "https://habitry.github.io" # the base hostname & protocol for your site

# Collections
collections:
  modules:
    output: true
    permalink: /:collection/:path/
    title: Modules
  habits:
    output: true
    permalink: /:path/
    title: Habits
  intros:
    output: true
    permalink: /:collection/:path/
    title: Introductions

# Contact settings
email: hello@habitry.com
twitter_username: habitry
github_username:  habitry

# Build settings
markdowm: kramdown

kramdown:
  input:      GFM
  auto_ids:   false

exclude: ["README.md", "LICENSE.md", "screenshot.png"]
